name: Detect Modified Files

on:
  push:
    branches:
      - master  # Replace with your branch name
  pull_request:
    branches:
      - master  # Replace with your branch name

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository with full commit history
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the full history to enable git diff

    # Step 2: Detect Modified Files
    - name: Detect Modified Files
      id: modified_files
      run: |
        MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "$MODIFIED_FILES" > modified_files.txt
        echo "MODIFIED_FILES=$MODIFIED_FILES" >> $GITHUB_ENV

    # Step 3: Upload modified_files.txt as an artifact
    - name: Upload Modified Files
      uses: actions/upload-artifact@v3
      with:
        name: modified-files
        path: modified_files.txt
