name: Fetch Modified Files

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fetch-modified-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Fetch modified files using git diff
      - name: Fetch modified files
        run: |
          git diff --name-only HEAD~1 > modified_files.txt
          echo "Modified files saved to modified_files.txt"
      
      # Step 3: Display the contents of modified_files.txt in the logs
      - name: Display Modified Files
        run: cat modified_files.txt
