name: Get Modified Files in Last Commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  identify-changed-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Identify files changed in the latest push
      - name: Get Recently Pushed Changes
        run: |
          git diff --name-only HEAD~1..HEAD > modified_files.txt
          echo "Modified files saved to modified_files.txt"

      # Step 3: Display the modified files in the logs
      - name: Show Changed Files
        run: |
          echo "Recently changed files in the latest push:"
          cat modified_files.txt

      # Step 4: Upload the modified_files.txt as an artifact
      - name: Upload Changed Files Artifact
        uses: actions/upload-artifact@v3
        with:
          name: recently-modified-files
          path: modified_files.txt

      # Step 5: Set up Java
     - name: Set up OpenJDK 8
  uses: actions/setup-java@v3
  with:
    java-version: 8  # Specifies OpenJDK 8 (Java 8)
    distribution: 'openjdk'  # Specifies the OpenJDK distribution
    check-latest: false   

      # Step 6: Compile Java Code
      - name: Compile Java Code
        run: |
          javac IdentifyImpactedTests.java

      # Step 7: Run Java Application
      - name: Run Java Application
        run: |
          java -cp . IdentifyImpactedTests
        env:
          MODIFIED_FILES_PATH: ${{ github.workspace }}/modified_files.txt
